name: snowex21
channels:
  - conda-forge
dependencies:
  - bokeh
  - cartopy
  - contextily
  - dask
  - dask-labextension
  - datashader
  - descartes
  - distributed
  - fiona
  - fsspec
  #- gcsfs
  - gdal
  - geoalchemy2
  - geojson
  - geopandas
  - geoviews
  - gh
  - git
  - h5py
  - holoviews
  - hvplot
  - icepyx
  - intake
  - intake-xarray
  - intake-stac
  - ipyleaflet
  - ipympl
  - ipywidgets
  - ipython-sql
  - jq
  - jupyter-book=0.10.2
  - jupyterhub-singleuser
  - jupyter-server-proxy
  - jupyterlab-git
  - jupyterlab=3
  - jupyter-resource-usage
  - matplotlib
  - nbgitpuller=0.9
  - numpy
  - pandas=1.2
  - panel
  - param>=1.11.1
  - pdal=2.2
  - pillow
  - pip
  - psycopg2
  - pyproj
  - python=3.8
  #- python-pdal=2.4=py38h1fd1430_1
  - pystac
  - rasterio
  - rasterstats
  - rioxarray
  - requests
  - s3fs
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - shapely
  - zarr
  - pip:
    - pystac-client
    - sphinxcontrib-bibtex==2.2.0
    - stackstac
    - git+https://github.com/snowex/snowexsql.git
    - git+https://github.com/snowex-hackweek/snowmicropyn.git@master
    - git+https://github.com/ICESat2-SlideRule/sliderule-python@v1.0.7